// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yubmcagfycimgennxzup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Ym1jYWdmeWNpbWdlbm54enVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NzA0ODgsImV4cCI6MjA3NjM0NjQ4OH0.E-XK5z2tZ4v4uWi2wuwRVySlDDIJu3c85JPUV90VETY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});